#!/usr/bin/env bun

/**
 * 华为内部构建脚本
 * 构建 Ubuntu x64 和 Windows x64 的 opencode 可执行文件
 *
 * 用法:
 *   bun ./script/build-huawei.ts [options]
 *
 * 选项:
 *   --output-dir <dir>  输出目录 (默认: ./dist-huawei)
 *   --version <ver>     自定义版本号 (默认: 从 package.json 读取)
 *   --skip-archive      跳过创建压缩包
 */

import { $ } from "bun"
import path from "path"
import fs from "fs"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

// 解析命令行参数
const args = process.argv.slice(2)
const getArg = (name: string, defaultValue: string) => {
  const idx = args.indexOf(name)
  return idx !== -1 && args[idx + 1] ? args[idx + 1] : defaultValue
}

const outputDir = path.resolve(dir, getArg("--output-dir", "./dist-huawei"))
const skipArchive = args.includes("--skip-archive")

// 读取版本号
const pkg = await Bun.file(path.join(dir, "package.json")).json()
const customVersion = getArg("--version", "")
const version = customVersion || pkg.version

console.log(`\n🚀 华为内部 OpenCode 构建脚本`)
console.log(`   版本: ${version}`)
console.log(`   输出目录: ${outputDir}\n`)

// 目标平台: Ubuntu x64 和 Windows x64
const targets = [
  { os: "linux", arch: "x64" as const, name: "opencode-linux-x64" },
  { os: "win32", arch: "x64" as const, name: "opencode-windows-x64" },
]

// 清理并创建输出目录
await $`rm -rf ${outputDir}`
await $`mkdir -p ${outputDir}`

// 导入构建依赖
const solidPlugin = (await import("../node_modules/@opentui/solid/scripts/solid-plugin")).default
const { Script } = await import("@opencode-ai/script")

// 获取或生成 models snapshot
const modelsJsonPath = process.env.MODELS_DEV_API_JSON
if (modelsJsonPath) {
  const modelsData = await Bun.file(modelsJsonPath).text()
  await Bun.write(
    path.join(dir, "src/provider/models-snapshot.ts"),
    `// Auto-generated by build-huawei.ts - do not edit\nexport const snapshot = ${modelsData} as const\n`,
  )
  console.log("✅ 使用本地 models.json 生成 models-snapshot.ts")
} else {
  console.log("⚠️  未设置 MODELS_DEV_API_JSON，使用现有的 models-snapshot.ts")
}

// 安装跨平台依赖
console.log("\n📦 安装跨平台依赖...")
await $`bun install --os="*" --cpu="*" @opentui/core@${pkg.dependencies["@opentui/core"]}`
await $`bun install --os="*" --cpu="*" @parcel/watcher@${pkg.dependencies["@parcel/watcher"]}`

const results: { name: string; path: string; archive?: string }[] = []

for (const target of targets) {
  console.log(`\n🔨 构建 ${target.name}...`)

  const distPath = path.join(outputDir, target.name)
  const binPath = path.join(distPath, "bin")
  await $`mkdir -p ${binPath}`

  const parserWorker = fs.realpathSync(path.resolve(dir, "./node_modules/@opentui/core/parser.worker.js"))
  const workerPath = "./src/cli/cmd/tui/worker.ts"

  // 根据目标平台设置 bunfs 路径
  const bunfsRoot = target.os === "win32" ? "B:/~BUN/root/" : "/$bunfs/root/"
  const workerRelativePath = path.relative(dir, parserWorker).replaceAll("\\", "/")

  const bunTarget = `bun-${target.os === "win32" ? "windows" : target.os}-${target.arch}`

  await Bun.build({
    conditions: ["browser"],
    tsconfig: "./tsconfig.json",
    plugins: [solidPlugin],
    sourcemap: "external",
    compile: {
      autoloadBunfig: false,
      autoloadDotenv: false,
      //@ts-ignore
      autoloadTsconfig: true,
      autoloadPackageJson: true,
      target: bunTarget as any,
      outfile: path.join(binPath, target.os === "win32" ? "opencode.exe" : "opencode"),
      execArgv: [`--user-agent=opencode/${version}`, "--use-system-ca", "--"],
      windows: {},
    },
    entrypoints: ["./src/index.ts", parserWorker, workerPath],
    define: {
      OPENCODE_VERSION: `'${version}'`,
      OTUI_TREE_SITTER_WORKER_PATH: bunfsRoot + workerRelativePath,
      OPENCODE_WORKER_PATH: workerPath,
      OPENCODE_CHANNEL: `'huawei'`,
      OPENCODE_LIBC: target.os === "linux" ? `'glibc'` : "",
    },
  })

  // 清理临时文件
  await $`rm -rf ${distPath}/bin/tui`.nothrow()

  // 写入版本信息
  await Bun.write(
    path.join(distPath, "version.json"),
    JSON.stringify({ version, platform: target.os, arch: target.arch, channel: "huawei" }, null, 2),
  )

  const result: { name: string; path: string; archive?: string } = {
    name: target.name,
    path: distPath,
  }

  // 创建压缩包
  if (!skipArchive) {
    if (target.os === "linux") {
      const archiveName = `${target.name}-${version}.tar.gz`
      const archivePath = path.join(outputDir, archiveName)
      await $`tar -czf ${archivePath} -C ${binPath} .`
      result.archive = archivePath
      console.log(`   📦 创建压缩包: ${archiveName}`)
    } else {
      const archiveName = `${target.name}-${version}.zip`
      const archivePath = path.join(outputDir, archiveName)
      await $`cd ${binPath} && zip -r ${archivePath} .`
      result.archive = archivePath
      console.log(`   📦 创建压缩包: ${archiveName}`)
    }
  }

  results.push(result)
  console.log(`   ✅ 构建完成: ${target.name}`)
}

// 输出构建结果
console.log(`\n${"=".repeat(50)}`)
console.log(`🎉 构建完成!\n`)
console.log(`输出目录: ${outputDir}`)
console.log(`\n构建产物:`)
for (const result of results) {
  console.log(`  - ${result.name}`)
  console.log(`    可执行文件: ${result.path}/bin/`)
  if (result.archive) {
    console.log(`    压缩包: ${result.archive}`)
  }
}

console.log(`\n使用方法:`)
console.log(`  Linux:   ${outputDir}/opencode-linux-x64/bin/opencode`)
console.log(`  Windows: ${outputDir}\\opencode-windows-x64\\bin\\opencode.exe`)

if (!skipArchive) {
  console.log(`\n发布压缩包:`)
  console.log(`  Linux:   ${outputDir}/opencode-linux-x64-${version}.tar.gz`)
  console.log(`  Windows: ${outputDir}/opencode-windows-x64-${version}.zip`)
}

console.log()
